### ISSUE TITLE
hstsparser.exe error

### ISSUE THREAD

**Issue by oasec1** [thebeanogamer/hstsparser#113]
Execution of the windows executable file, hstsparser.exe; generated this error

command line used - c:\tools\hstsparser.exe --chrome "C:\Users\joe\Downloads\TransportSecurity

Traceback (most recent call last):
  File "hstsparser.py", line 228, in <module>
  File "hstsparser.py", line 183, in main
TypeError: list indices must be integers or slices, not str
[15220] Failed to execute script 'hstsparser' due to unhandled exception!

Can you help?

Thanks
Robert

**Comment by thebeanogamer** [comment]
Hey Robert,

It appears that Chrome has redesigned this file since I did my original research. I'm working on an update now to support the new format which I will hopefully release today.

Can I ask how you found this tool?

Thanks.

**Comment by thebeanogamer** [comment]
I've release version 1.2.0 with this fix merged in. You can download the updated version on https://github.com/thebeanogamer/hstsparser/releases/tag/1.2.0 or from PyPi.

**Comment by oasec1** [comment]
I found it as a result of an investigation I was performing around the history if Chrome. Not too much out there about it but this is great tool. Any thoughts on adding a search functionality for any forensic evidence image files that may be mounted as a drive?

Best Regards,
Robert
