### ISSUE TITLE
hstsparser: error: The file FILE does not exist!

### ISSUE THREAD

**Issue by oasec1** [thebeanogamer/hstsparser#115]
Running the Windows executable, performing Chrome Analysis, I've verified the file, TransportSecurity exists in that path specified with the commandline.

hstsparser.exe --chrome.exe FILE "C:\Users\XXX\Desktop\YYYY\Work\results\TransportSecurity"

Thanks
Robert

**Comment by thebeanogamer** [comment]
Hey Robert,

You don't need to include the word `FILE` there. That's a placeholder for you to put your filepath.

I think what you should run is this:

```shell
hstsparser.exe --chrome.exe "C:\Users\XXX\Desktop\YYYY\Work\results\TransportSecurity"
```

Thanks.
